CREATE TABLE EMP_DDL(
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(10),
    JOB         VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
    );
CREATE TABLE DEPT_DDL AS SELECT * FROM DEPT; DESC DEPT_DDL;
SELECT * FROM DEPT_DDL;
CREATE TABLE EMP_DDL_30 AS SELECT * FROM EMP WHERE DEPTNO = 30; SELECT * FROM EMP_DDL_30;
CREATE TABLE EMPDEPT_DDL AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC FROM EMP E, DEPT D WHERE 1 <> 1; SELECT * FROM EMPDEPT_DDL;
CREATE TABLE EMP_ALTER AS SELECT * FROM EMP; SELECT * FROM EMP_ALTER;
ALTER TABLE EMP_ALTER ADD HP VARCHAR2(20); SELECT * FROM EMP_ALTER;
ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL;SELECT * FROM EMP_ALTER;
ALTER TABLE EMP_ALTER MODIFY EMPNO NUMBER(5); DESC EMP_ALTER;
ALTER TABLE EMP_ALTER DROP COLUMN TEL; SELECT * FROM EMP_ALTER;
RENAME EMP_ALTER TO EMP_RENAME; DESC EMP_RENAME;
SELECT * FROM EMP_RENAME;
TRUNCATE TABLE EMP_RENAME;
DROP TABLE EMP_RENAME;
CREATE TABLE EMP_HW(
EMPNO NUMBER(4), ENAME VARCHAR2(10), JOB VARCHAR2(9), MGR NUMBER(4), HIREDATE DATE, SAL NUMBER(5,2), COMM NUMBER(5,2), DEPTNO NUMBER(2));
ALTER TABLE EMP_HW ADD BIGO VARCHAR(20);
SELECT * FROM EMP_HW;
DESC EMP_HW
ALTER TABLE EMP_HW MODIFY BIGO VARCHAR2(30);
ALTER TABLE EMP_HW RENAME COLUMN BIGO TO REMARK;
ALTER TABLE EMP_HW MODIFY SAL NUMBER(7,2); 
ALTER TABLE EMP_HW MODIFY COMM NUMBER(7,2); 



INSERT INTO EMP_HW 
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL 
  FROM EMP; 
  
DESC EMP;
SELECT * FROM EMP_HW;
DROP TABLE EMP_HW;
DESC EMP_HW;