SELECT * FROM DICT;
SELECT * FROM DICTIONARY;
SELECT TABLE_NAME FROM USER_TABLES;
SELECT OWNER, TABLE_NAME FROM ALL_TABLES;
SELECT * FROM DBA_TABLES; --FROM SCOTT
SELECT * FROM DBA_TABLES; --FROM SYSTEM 
SELECT * FROM DBA_USERS WHERE USERNAME = 'SCOTT';
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;
CREATE INDEX IDX_EMP_SAL ON EMP(SAL);
SELECT * FROM USER_IND_COLUMNS;
DROP INDEX IDX_EMP_SAL;
SELECT * FROM USER_IND_COLUMNS;

CREATE VIEW VW_EMP20 AS (SELECT EMPNO, ENAME, JOB, DEPTNO FROM EMP WHERE DEPTNO = 20);
SELECT * FROM USER_VIEWS;
SELECT VIEW_NAME, TEXT_LENGTH, TEXT FROM USER_VIEWS;
SELECT * FROM VW_EMP20;
DROP VIEW VW_EMP20;
SELECT ROWNUM, E.* FROM EMP E;
SELECT ROWNUM, E.* FROM EMP E ORDER BY SAL DESC;
SELECT ROWNUM, E.* FROM (SELECT * FROM EMP E ORDER BY SAL DESC) E;
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC) SELECT ROWNUM, E.* FROM E;
SELECT ROWNUM, E.* FROM (SELECT * FROM EMP ORDER BY SAL DESC) E WHERE ROWNUM <= 3;
WITH E AS(SELECT * FROM EMP ORDER BY SAL DESC) SELECT ROWNUM, E.* FROM E WHERE ROWNUM <= 3;
CREATE TABLE DEPT_SEQUENCE AS SELECT * FROM DEPT WHERE 1<>1; SELECT * FROM DEPT_SEQUENCE;
CREATE SEQUENCE SEQ_DEPT_SEQUENCE INCREMENT BY 10 START WITH 10 MAXVALUE 90 MINVALUE 0 NOCYCLE CACHE 2;
SELECT * FROM USER_SEQUENCES;
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL'); SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL'); SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
ALTER SEQUENCE SEQ_DEPT_SEQUENCE INCREMENT BY 3 MAXVALUE 99 CYCLE;
SELECT * FROM USER_SEQUENCES;
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL'); SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;
DROP SEQUENCE SEQ_DEPT_SEQUENCE; SELECT * FROM USER_SEQUENCES;


CREATE SYNONYM E FOR EMP;
SELECT * FROM E;
DROP SYNONYM E;